services:

    orbitale_cms.listeners.layouts:
        class: Orbitale\Bundle\CmsBundle\EventListener\LayoutsListener
        arguments:
            - '%orbitale_cms.config%'
            - "@templating"
        tags:
          - { name: kernel.event_subscriber }

    orbitale_cms.twig.extension:
        class: Orbitale\Bundle\CmsBundle\Twig\CmsExtension
        arguments:
            - '%orbitale_cms.config%'
        tags: [ { name: twig.extension } ]

    # These are the Gedmo services needed to manage Doctrine Extensions.
    # Tags are added from the DI Extension.
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
