services:
    orbitale_cms.listeners.layouts:
        class: Orbitale\Bundle\CmsBundle\EventListener\LayoutsListener
        arguments:
            config: '%orbitale_cms.config%'
            templating: "@templating"
        tags:
          - { name: kernel.event_subscriber }

    orbitale_cms.twig.extension:
        class: Orbitale\Bundle\CmsBundle\Twig\CmsExtension
        arguments:
            - '%orbitale_cms.config%'
        tags: [ { name: twig.extension } ]

    # These are the Gedmo services needed to manage Doctrine Extensions
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: '%orbitale_cms.connection%' }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: '%orbitale_cms.connection%' }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
