# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    pierstoval_cms.listeners.layouts:
        class: Pierstoval\Bundle\CmsBundle\Listeners\LayoutsListener
        arguments:
            config: %pierstoval_cms.config%
            templating: @templating
        tags:
          - { name: kernel.event_subscriber }
