services:
    orbitale_cms.page_repository:
        class: Orbitale\Bundle\CmsBundle\Repository\PageRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "%orbitale_cms.page_class%"
        calls:
            - [ 'setConfig', ['%orbitale_cms.config%'] ]

    orbitale_cms.category_repository:
        class: Orbitale\Bundle\CmsBundle\Repository\CategoryRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "%orbitale_cms.category_class%"
        calls:
            - [ 'setConfig', ['%orbitale_cms.config%'] ]
