services:
    orbitale_cms.listeners.layouts:
        class: Orbitale\Bundle\CmsBundle\EventListener\LayoutsListener
        arguments:
            config: '%orbitale_cms.config%'
            templating: "@templating"
        tags:
          - { name: kernel.event_subscriber }

    orbitale_cms.twig.extension:
        class: Orbitale\Bundle\CmsBundle\Twig\CmsExtension
        arguments:
            - '%orbitale_cms.config%'
        tags: [ { name: twig.extension } ]
