services:
    orbitale_cms.listeners.layouts:
        class: Orbitale\Bundle\CmsBundle\EventListener\LayoutsListener
        arguments:
            - '%orbitale_cms.layouts%'
            - "@templating"
        tags:
          - { name: kernel.event_subscriber }

    orbitale_cms.twig.extension:
        class: Orbitale\Bundle\CmsBundle\Twig\CmsExtension
        arguments:
            - '%orbitale_cms.design%'
        tags: [ { name: twig.extension } ]

    orbitale_cms.doctrine_mapping_listener:
        class: Orbitale\Bundle\CmsBundle\EventListener\DoctrineMappingListener
        public: false
        arguments:
            - "%orbitale_cms.page_class%"
            - "%orbitale_cms.category_class%"
        tags:
            - { name: doctrine.event_subscriber }
