orbitale_cms_category:
    path: /{slugs}
    requirements:
        slugs: '([a-zA-Z0-9_-]+\/?)+'
    defaults:
        _controller: Orbitale\Bundle\CmsBundle\Controller\CategoryController::indexAction
