orbitale_cms_page:
    path: /{slugs}
    requirements:
        slugs: "([a-zA-Z0-9_-]+\/?)*"
    defaults:
        _controller: Orbitale\Bundle\CmsBundle\Controller\PageController::indexAction
        slugs: ''
