orbitale_cms_post:
  path: /{date}/{slugs}
  requirements:
    slugs: "([a-zA-Z0-9_-]+\/?)*"
  defaults:
    _controller: Orbitale\Bundle\CmsBundle\Controller\PostController::indexAction
    _date_format: "Y/m/d"