name: PHP CI

on: [push]

jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version:
                    - '7.3'
                    - '7.4'
                    - '8.0'
                    - '8.1'

                symfony-version:
                    - '5.3'
                    - '5.4'
                    - '6.0'

                exclude:
                    - php-version: 7.3
                      symfony-version: 6.0
                    - php-version: 7.4
                      symfony-version: 6.0

        name: PHP ${{ matrix.php-version }} and Symfony ${{ matrix.symfony-version }}
        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: "${{ matrix.php-version }}"
                  extensions: pdo, pdo_mysql

            - run: composer validate

            - id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Update Symfony version
              run: |
                  sed -i composer.json -e 's/\^5\.0\(.[0-9]\+\)\?[|]\^6\.0/${{ matrix.symfony-version }}.*/g'

            - run: composer install

            - run: vendor/bin/simple-phpunit --version

            - run: vendor/bin/simple-phpunit
